name: bactflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies: 
  - curl
  - pkg-config
  - python=3.10
  - minimap2=2.28
  - checkm-genome
  - flye
  - mummer
  - medaka
  - pplacer
  - gtdbtk
  - hmmer
  - prodigal
  - unicycler
  - spades
  - megahit
  - nanofilt
  - rasusa
  - miniasm
  - racon
  - samtools
  - bcftools
  - git
  - pip
  - seqkit
  - fastani
  - skani
  - parallel
  - pomoxis
  - pip:
    - pyCirclize
    - circlator
    - pytmler
    - bokeh
    - numpy
    - h5py
    - pandas
    - pysam
    - biopython
    - flask
    - quast
  - prokka
  - r-base=4.4
  - r-ggplot2
  - r-dplyr
  - r-biocmanager


      

